server:
  port: 9772

logging:
  level:
    console: WARN
    filter: WARN

# rabbitMQ/Mysql/Redis ip，端口，帐号等根据环境自行修改。
spring:
  profiles:
    active: prod2
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    password: guest
    username: guest
  redis:
    host: zuihou.redis.host
    port: 6379
    key-prefix: prod  # redis key的前缀， 环境的多个实例一定要配置一样（即prod1和prod2文件中需要配置一致）
