prod1:
  eureka:
    server:
      port: 8501
    hostname: eureka1.zuihou.com
prod2:
  eureka:
    server:
      port: 8502
    hostname: eureka2.zuihou.com
dev:
  eureka:
    server:
      port: 8500
    hostname: eureka.zuihou.com

logging:
  path: ./logs/zuihou-config
  file: ${logging.path}/root.log
  common-pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS}:[%5p] [%t:%r] [%C{1}:%M:%L] --> %m%n'
  level:
    console: INFO

# 公共配置
spring:
  profiles:
    active: dev
  application:
    name: zuihou-config
  cloud:
    config:
      label: Edgware
      server:
        git:
          uri: https://gitee.com/zuihou111/zuihou-admin-cloud
#          uri: https://gitee.com/zuihou111/zuihou-admin-cloud-config-repo
          search-paths: zuihou-config-repo/*/{application}
  rabbitmq:
    host: zuihou.rabbitmq.host
    port: 5672
    password: guest
    username: guest

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD:admin}
endpoints:
  health:
    enabled: true
    sensitive: true  # actuator的health接口是否需要安全保证

# info 信息放在仓库中，无法动态获取属性
info:
  artifact: zuihou-config
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'