# info 信息放在仓库中，无法动态获取属性
info:
  artifact: zuihou-zipkin
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'
  spring-cloud-version: '@spring.cloud.version@'

#zipkin:
#  storage:
#    type: mysql
#  collector:
#    http:
#      enabled: false
#    rabbitmq:
#      addresses: zuihou.rabbitmq.host:5672
#      username: guest
#      password: guest
#      queue: zipkin