lamp:
  rabbitmq:
    # 若系统中有除了zipkin之外的地方使用了mq ，则一定不能设置成false
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: lamp
    password: lamp

spring:
  rabbitmq:
    enabled: ${lamp.rabbitmq.enabled}
    host: ${lamp.rabbitmq.ip}
    port: ${lamp.rabbitmq.port}
    username: ${lamp.rabbitmq.username}
    password: ${lamp.rabbitmq.password}
    listener:
      type: direct # simple direct
